name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Debug submodules
      run: |
        git submodule status
        git submodule foreach 'git status'
    - name: Install Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential
    - name: Setup mruby
      run: |
        git clone -b 3.3.0 https://github.com/mruby/mruby.git
        cd mruby
        rake
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    - name: Build PicoRuby
      run: rake
    - name: Test with mruby/c
      run: mrbgems/mruby-compiler2/test/helper/test.rb
      env:
        MRUBY_COMMAND: $PWD/bin/picoruby
    - name: Test with mruby
      run: mrbgems/mruby-compiler2/test/helper/test.rb
      env:
        USE_MRUBY: yes
        PICORBC_COMMAND: $PWD/bin/picorbc
        MRUBY_COMMAND: $PWD/mruby/bin/mruby
